config/routes.rb
Rails.application.routes.draw do

  get 'bank_accounts/unallocated'
  get 'purchases/paid'
  get 'purchases/draft_index'
  get 'purchases/unpaid'
  get 'purchases/partially_paid'
  get 'report/income_statement'
  get 'report/balance_sheet'
  get 'report/trial_balance'
  get 'report/general_ledger'
  get 'payment_entries/invoice_entry'
  get 'receipt_entries/invoice_entry'
   get 'sales/paid'
  get 'sales/draft_index'
  get 'sales/unpaid'
  get 'sales/partially_paid'
  resources :journals
  resources :journal_entries
  resources :products
    get 'purchases/draft'
   get 'purchases/invoice'
  resources :purchase_entries
  resources :purchases
  resources :contacts
  get 'sales/quote'
  get 'sales/draft'
   get 'sales/invoice'
  resources :sales_entries
  resources :sales
  resources :receipt_entries
  resources :payment_entries
  resources :bank_accounts
  resources :gl_accounts
  resources :transactions
  get 'index/home'
 
  root 'index#home'
  
    resources :transactions do 
    collection { post :import }
  end
  resources :bank_accounts do 
    collection { post :import }
  end
  
   resources :transactions do
    collection do
      delete 'destroy_multiple'
    end
  end
 
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
    @purchase_entry = PurchaseEntry.all
  end
  
    def paid
    @purchases = Purchase.all
    @purchase_entry = PurchaseEntry.all
    @transactions = Transaction.all
  end
  
  def unpaid
    @purchases = Purchase.all
   
  end
  
    def partially_paid
    @purchases = Purchase.all
    @purchase_entry = PurchaseEntry.all
    @transactions = Transaction.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @purchase_entry = PurchaseEntry.all
    @transactions = Transaction.all
  end
  
     def draft_index
     @purchases = Purchase.where("purchases_type =?", 1)
    @purchase_entry = PurchaseEntry.all
  end
  

  # GET /purchases/new
  def new
    @purchase = Purchase.new
    @purchase.purchase_entries.build
  end
  
   def invoice
    @purchase = Purchase.new
    @purchase.purchase_entries.build
  end
  
   def draft
    @purchase = Purchase.new
    @purchase.purchase_entries.build
  end
  



  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:invoice_number, :contact_id, :date, :notes, :purchases_type, :user_id, :amount, :purchase_id, :id, purchase_entries_attributes: [:id, :product_id, :description, :gl_account_id, :account_id, :quantity, :price, :total_price, :purchase_id, :user_id])
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= simple_form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>
      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
<div class= "card col-md-12">
  <div class="card-header card-header-info">
                                    <strong><h3 class="card-title">Edit Invoice</h3></strong>
                                    <p class="card-category"></p>
                                     </div> 
   <table class = "table">
    <thead>
      <tr><center>
    <th>  <%= f.label :date %><br></th>
   <th> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td></th>
   <th></th>
   <th>  <%= f.label :customer_id %><br></th>
    <th> <%= f.collection_select(:contact_id, Contact.all, :id, :name, {:prompt => false},  class: 'form-control')  %></th>
    <th>  <%=  f.text_field :invoice_number, class: 'btn btn-default pull-right'  %></th>
    <th>  <%=  f.select :purchases_type, Purchase.purchases_types.keys, {}, class: 'btn btn-default pull-right'  %></th>
   </tr></center>
   <th></th>
  </div>
 </div>

</div>
  </br></br></br>
  
 
<div class= "card">
  <table class = "table">
    <thead>
    <tr>
      <th class ="colspan-1"></th>
       <th class ="colspan-1">Product</th>
      <th class ="colspan-1">Description</th>
      <th class ="col-md-0.1">Account</th>
      <th class ="colspan-1">Vat</th>
      <th class ="colspan-1">Quantity</th>
      <th class ="colspan-1">Amount</th>
      <th class ="colspan-1">Total</th>
    </tr>
  </thead>
    

      <div class = "card">
 <tbody class ="fields">
    <%= f.fields_for :purchase_entries do |builder| %>
    <%= render 'purchase_entry', f: builder %>
    <% end %>
    </div>
  </div>
  </tbody>
  
  </table>
  <%= link_to_add_row('Add line', f, :purchase_entries, class: 'btn btn-warning') %>
  </br> </br>
   <%= f.text_area :notes, class: 'form-control', placeholder: 'Notes' %> 
  </div>
  <div class="actions">

    </br></br>
     <%= f.submit 'Create Invoice', :class => 'btn btn-success' %> | <%= link_to 'Back', sales_path, class:"btn btn-default" %>

  </div>
<% end %>
 </center>
 
 
 

app/views/purchases/_purchase_entry.html.erb
<tr>
    <td>
        <%= f.hidden_field :_destroy %>
        <%= link_to "remove", '#', class: "remove_record" %>
    </td>
      <td class="col-md-1"> <%= f.collection_select :product_id, Product.all, :id, :name, {:prompt => false},class:"btn btn-sm" %></td>
     <td><%= f.text_field :description, label: false, class:"form-control" %></td>
    <td><%= f.collection_select :gl_account_id, GlAccount.all, :id, :name, {:prompt => false},class:"btn btn-sm" %></td>
    <td><%= f.collection_select :vat_type, PurchaseEntry.vat_types.map{ |dp| [dp.first, dp.first.humanize] }, :first, :second,{:prompt => false},class:"btn btn-sm"  %></td>
    <td><%= f.text_field :quantity, label: false, class:"form-control qty"%></td>
    <td><%= f.text_field :price, label: false, class:"form-control price"%></td>
    <td id="amount"><p class='amount' id-"amount">0.00</p></td>
    
    
     
</tr>

app/views/purchases/draft.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>
      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
<div class= "card col-md-10">
  <div class="card-header card-header-warning">
                                    <h4 class="card-title">Draft Purchase Invoice</h4>
                                    <p class="card-category"></p>
                                     </div> 
   <table class = "table">
    <thead>
      <tr><center>
    <th>  <%= f.label :date %><br></th>
   <th> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td></th>
   <th></th>
   <th>  <%= f.label :customer_id %><br></th>
    <th> <%= f.collection_select(:contact_id, Contact.all, :id, :name, {:prompt => false},  class:"btn ml-auto")  %></th>
  <th>  <%=  f.text_field :invoice_number, placeholder: "Invoice number", class: 'form-control'  %></th>
    <th>  <%=  f.select :purchases_type, Purchase.purchases_types.keys, {}, class: 'btn btn-default pull-right'  %></th>
   </tr></center>
   <th></th>
  </div>
 </div>

</div>
  </br></br></br>
  
 
<div class= "card">
  <table class = "table">
    <thead>
    <tr>
      <th class ="colspan-1"></th>
       <th class ="colspan-1">Product</th>
      <th class ="colspan-1">Description</th>
      <th class ="colspan-1">Account</th>
      <th class ="colspan-1">Vat</th>
      <th class ="colspan-1">Quantity</th>
      <th class ="colspan-1">Amount</th>
      <th class ="colspan-1">Total</th>
    </tr>
  </thead>
    

      <div class = "card">
 <tbody class ="fields">
    <%= f.fields_for :purchase_entries do |builder| %>
    <%= render 'purchase_entry', f: builder %>
    <% end %>
    </div>
  </div>
  </tbody>
  
  </table>
  <%= link_to_add_row('Add line', f, :purchase_entries, class: 'btn btn-warning') %>
  </br> </br>
   <%= f.text_area :notes, class: 'form-control', placeholder: 'Notes' %> 
  </div>
  <div class="actions">

    </br></br>
     <%= f.submit 'Create Invoice', :class => 'btn btn-success' %> | <%= link_to 'Back', purchases_path, class:"btn btn-default" %>

  </div>
<% end %>
 </center>
 
 
 

app/views/purchases/draft_index.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', purchases_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', purchases_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', purchases_paid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', purchases_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', purchases_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', purchases_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
  
      <tr>
        <td><%= link_to purchase.date, purchase_path(purchase) %></td>
        <td><%= purchase.contact_id ? purchase.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{purchase.id}" %></td>
        
        
             <% purchase.amount  = 0 %>
        <% @purchase_entry.each do |entry| %>
        <% if purchase.id == entry.purchase_id %>
         <% purchase.amount += entry.total_price.to_f %>
          <% end %>
           <% end %>
           <td><%= purchase.amount %></td>
      
      
             <td>    <% if purchase.purchases_type == 'invoice' %>
            <%= link_to "Invoice", edit_purchase_path(purchase), class:"btn btn-success" %></td>
           
            <% else if purchase.purchases_type == 'draft' %>
            <%= link_to "Draft", edit_purchase_path(purchase), class:"btn btn-danger" %>
  
          
             <% end %>
             <% end %>
      </td>   
        <td><%= link_to "Edit", edit_purchase_path(purchase) %> | <%= link_to 'Delete', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/purchases/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', purchases_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', purchases_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', purchases_paid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', purchases_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', purchases_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', purchases_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= link_to purchase.date, purchase_path(purchase) %></td>
        <td><%= purchase.contact_id ? purchase.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{purchase.id}" %></td>
        
        
             <% purchase.amount  = 0 %>
        <% @purchase_entry.each do |entry| %>
        <% if purchase.id == entry.purchase_id %>
         <% purchase.amount += entry.total_price.to_f %>
          <% end %>
           <% end %>
           <td><%= purchase.amount %></td>
      
      
             <td>    <% if purchase.purchases_type == 'invoice' %>
            <%= link_to "Invoice", edit_purchase_path(purchase), class:"btn btn-success" %></td>
           
            <% else if purchase.purchases_type == 'draft' %>
            <%= link_to "Draft", edit_purchase_path(purchase), class:"btn btn-danger" %>
  
             <% end %>
             <% end %>
      </td>   
        <td><%= link_to "Edit", edit_purchase_path(purchase) %> | <%= link_to 'Delete', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/purchases/invoice.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>
      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
<div class= "card col-md-12" id="purchase">
  <div class="card-header card-header-success">
                                    <h4 class="card-title">Draft Purchase Invoice</h4>
                                    <p class="card-category"></p>
                                     </div> 
   <table class = "table">
    <thead>
      <tr><center>
    <th>  <%= f.label :date %><br></th>
   <th> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td></th>
   <th></th>
   <th>  <%= f.label :customer_id %><br></th>
    <th> <%= f.collection_select(:contact_id, Contact.all, :id, :name, {:prompt => false},  class:"btn ml-auto")  %></th>
     <th>  <%=  f.text_field :invoice_number, placeholder: "Invoice number", class: 'form-control'  %></th>
    <th class="purchase_type">  <%=  f.select :purchases_type, Purchase.purchases_types.keys, {}, class: 'btn btn-default pull-right'  %></th>
   </tr></center>
   <th></th>
  </div>
 </div>

</div>
  </br></br></br>
  
 
<div class= "card">
  <table class= "table">
    <thead>
    <tr>
      <th class ="colspan-1"></th>
       <th class ="colspan-1">Product</th>
      <th class ="colspan-1">Description</th>
      <th class ="colspan-1">Account</th>
       <th class="col-md-1">Vat</th>
      <th class ="colspan-1">Quantity</th>
      <th class ="colspan-1">Amount</th>
      <th class ="colspan-1">Total</th>
    </tr>
  </thead>
    

      <div class = "card">
 <tbody class ="fields" id="myTable">
    <%= f.fields_for :purchase_entries do |builder| %>
    <%= render 'purchase_entry', f: builder %>
    <% end %>
    </div>
  </div>

  </tbody>
  
  <tr>
     <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td><h5>Total: </h5></td>
 <td><strong><h5 class="total"></h5></strong></td>
 </tr>
  </table>
  <%= link_to_add_row('Add line', f, :purchase_entries, class: 'btn btn-warning') %>
  </br> </br>
   <%= f.text_area :notes, class: 'form-control', placeholder: 'Notes' %> 
  </div>
  <div class="actions">

    </br></br>
     <%= f.submit 'Create Invoice', :class => 'btn btn-success' %> | <%= link_to 'Back', purchases_path, class:"btn btn-default" %>

  </div>
<% end %>
 </center>
 
 
 

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/paid.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', purchases_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', purchases_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', purchases_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', purchases_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', purchases_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', purchases_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th> Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
    <% if (purchase.balance.to_f * -1 ) >= purchase.amount.to_f %>
      <tr>
        <td><%= link_to purchase.date,  purchase_path(purchase)%></td>
        <td><%= purchase.contact_id ? purchase.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{purchase.id}" %></td>
             <td><%= purchase.amount %></td>
              <td> <%= purchase.balance %> </td>
              <td> <%= purchase.amount + purchase.balance %> </td>
             <% end %>
              <% end %>
      </td>   
      
      </tr>

  </tbody>
</table>
</div>

<br>

app/views/purchases/partially_paid.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', purchases_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', purchases_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', purchases_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', purchases_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', purchases_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', purchases_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th> Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
    <% if purchase.balance.to_f * -1 < purchase.amount.to_f && purchase.balance != nil%>
      <tr>
        <td><%= link_to purchase.date,  purchase_path(purchase)%></td>
        <td><%= purchase.contact_id ? purchase.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{purchase.id}" %></td>
             <td><%= purchase.amount %></td>
              <td> <%= purchase.balance %> </td>
              <td> <%= purchase.amount + purchase.balance %> </td>
             <% end %>
              <% end %>
      </td>   
      
      </tr>

  </tbody>
</table>
</div>

<br>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<center>

<div class= "card col-md-10" style="background-color:#f2f2f2;">
 
  <% if @purchase.purchases_type == "invoice" %>
                <div class="card-header card-header-success">
                    <h4 class="card-title">purchase</h4>
                      <p class="card-category"></p>
                      </div> 
                              <% else if @purchase.purchases_type == "draft" %>
                               <div class="card-header card-header-danger">
                                 <h4 class="card-title">Draft</h4>
                                   <p class="card-category"></p>
                                           </div> 
                                           <% else if @purchase.purchases_type == "Quote" %>
                                             <div class="card-header card-header-warning">
                                               <h4 class="card-title">Draft</h4>
                                                 <p class="card-category"></p>
                                           </div> 
                                     <% end %>
                                     <% end %>
                                     <% end %>
   <table class = "table">
    <thead >
      <tr><center>
    <th>Date: </th>
   <th>  <%= @purchase.date %> </td></th>
   <th></th>
   <th> <strong>Invoice Type:</strong><br></th>
    <th>  <%= @purchase.purchases_type %></th>
     <th> <strong>Customer:</strong><br></th>
    <th><%= @purchase.contact_id ? @purchase.contact.name : '' %> </br>
       <%= @purchase.contact_id ? @purchase.contact.address_one : '' %> </br>
      <%= @purchase.contact_id ? @purchase.contact.city : '' %> </br>
   </tr></center>
  </div>
 </div>

</div>
  </br></br></br>
  
<div class= "card">

  <table class = "table">
    <thead style="background-color:#fff;">
    <tr>
      <th>Description</th>
       <th>Product</th>
      <th>Account</th>
      <th>Quantity</th>
       <th>Vat</th>
       <th>Net Amount</th>
        <th>Total</th>


  </thead>
        <h3><left>Invoice Items</left></h3>
      <tbody style="background-color:#fff;">
       <% @purchase_entry.each do |entry| %>
            <% if entry.purchase_id == @purchase.id %>

               <td>  <%= entry.description %></td>
                <td> <%= entry.product_id ? entry.product.name : ' ' %></td>
               <td> <%= entry.gl_account ? entry.gl_account.name : ' ' %></td>
                 <td> <%= entry.quantity %></td>
                  <td> <%= entry.vat_amount.to_f.round(2) %></td>
                   <td> <%= entry.net_price.to_f.round(2) %></td>
                     <td><strong><%= entry.price.round(2)  %></strong></td>
              </tr>
                <% end %>
                    <% end %>
   </table>
   
   <h3 class='pull-left'>Payments</h3>
   
   <table class="table">
       </br>
      <thead style="background-color:#fff;">

     
      <th><strong>Date</strong></th>
       <th><strong>Description</strong></th>
      <th><strong>Reference</strong></th>
      <th></th>
      <th></th>
      <th></th>
      <th><strong>Amount</strong></th>

    </tr>
    <br>
    <br>
      <tr>
      <% @transactions.each do |transaction| %>
      <% if transaction.purchase_id == @purchase.id %>
      
           <td><%= transaction.date %></td>
           <td><%=  transaction.description %></td>
          <td><%=transaction.reference %></td>
           <td></td>
          <td></td>
          <td></td>
          <td><%= transaction.total_amount %></td>
          </tr>
          
     <% end %>
     <% end %>
  
      
      
      </tbody>
      </table>
      </br></br>
      <h3>Balance</h3>
      <table class ="table">
      <tbody style="background-color:#fff;">
        <tr>
        <td><strong>Balance:</strong></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
         <td></td>
             
             <td><strong><%= @purchase.amount.to_f + @purchase.balance.to_f %> </strong></td>
       
            
          </tbody>
          
  </table>
  </div>
  <%= link_to 'Edit', edit_purchase_path(@purchase), class: "btn btn-default" %> |
<%= link_to 'Back', purchases_path ,class:"btn btn-default"%>
 </center>

 
 

app/views/purchases/unpaid.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', purchases_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', purchases_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', purchases_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', purchases_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', purchases_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', purchases_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th> Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
    <% if purchase.balance == nil %>
      <tr>
        <td><%= link_to purchase.date,  purchase_path(purchase)%></td>
        <td><%= purchase.contact_id ? purchase.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{purchase.id}" %></td>
             <td><%= purchase.amount %></td>
              <td> <%= purchase.amount  %> </td>
             <% end %>
              <% end %>
      </td>   
      
      </tr>

  </tbody>
</table>
</div>

<br>