config/routes.rb
Rails.application.routes.draw do

  get 'bank_accounts/unallocated'
  get 'purchases/paid'
  get 'purchases/draft_index'
  get 'purchases/unpaid'
  get 'purchases/partially_paid'
  get 'report/income_statement'
  get 'report/balance_sheet'
  get 'report/trial_balance'
  get 'report/general_ledger'
  get 'payment_entries/invoice_entry'
  get 'receipt_entries/invoice_entry'
   get 'sales/paid'
  get 'sales/draft_index'
  get 'sales/unpaid'
  get 'sales/partially_paid'
  resources :journals
  resources :journal_entries
  resources :products
    get 'purchases/draft'
   get 'purchases/invoice'
  resources :purchase_entries
  resources :purchases
  resources :contacts
  get 'sales/quote'
  get 'sales/draft'
   get 'sales/invoice'
  resources :sales_entries
  resources :sales
  resources :receipt_entries
  resources :payment_entries
  resources :bank_accounts
  resources :gl_accounts
  resources :transactions
  get 'index/home'
 
  root 'index#home'
  
    resources :transactions do 
    collection { post :import }
  end
  resources :bank_accounts do 
    collection { post :import }
  end
  
   resources :transactions do
    collection do
      delete 'destroy_multiple'
    end
  end
 
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end
  
  def import
     Transaction.import(params[:file])
     redirect_to :back, notice: "Transactions imported."
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    end



  # GET /transactions/1/edit
  def edit
  end

def destroy_multiple

  Transaction.destroy(params[:transactions])

  respond_to do |format|
    format.html { redirect_to blog_posts_path }
    format.json { head :no_content }
  end

end


  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html {redirect_to :back, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html {redirect_to :back, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:id, :payment,  :date, :description, :amount, :reference, :bank_account_id, :purchase_id, :sale_id, :total_amount, :bank_id, :account_id, :payment_entry_id, :purchase_invoice_id, :sales_invoice_id, :contact_id, :vat_amount, :vat, :gl_account_id, :vat_type)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="form-fields">
<%= simple_form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <center>
<center><div class="justify-content-md-center">
  <div class="col-lg-12 col-md-12">
  <div class = "card">
   <div class="card-header card-header-success">
                                    <h4 class="card-title">New Transaction</h4>
                                    <p class="card-category"></p>
                                     </div> 
    <div class="card-text">
  <form class="needs-validation" novalidate>
  <table class = "table">
    <thead>
    <tr>
      <th class ="colspan-1"></th>
      <th class ="colspan-1">Date</th>
       <th class ="colspan-1">Description</th>
      <th class ="colspan-1">Reference</th>
       <th class ="colspan-1">Bank</th>
      <th class ="colspan-1">Account</th>
        <th class ="col-md-1">Vat</th>
      <th class ="colspan-1">Amount</th>
    </tr>
  </thead>
  
  
  <tr>
    <td>
         
              <%= f.hidden_field :_destroy %>
              <%= link_to "remove", '#', class: "remove_record" %>

    </td>
    <td>
      <td><select id="select_option">
  <option value="home">Home</option>
  <option value="office">Office</option>
</select>
</td>
   <td> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td>
    <td><%= f.text_field :description, label: false, class: 'form-control input'  %></td>
        <td><%= f.text_field :reference, label: false, class: 'form-control input'  %></td>
        <td>  <%= f.collection_select :bank_account_id, BankAccount.all, :id, :name, {:prompt => false},class:"btn" %></td>
        <td><%= f.collection_select :gl_account_id, GlAccount.all, :id, :name, {:prompt => false},class:"btn", id:"office_address"%></td>
        <td><%= f.input :vat_type, as: :select, label: " '", collection: Transaction.vat_types.map { |key, value| [key.humanize, key] }, class: "btn" %></td>
        <td> <%= f.text_field :amount, class: 'form-control input'  %></td>
        <%  f.check_box :payment, :value => true %>
     
    </table>
</div>

    </div>
 <div class="actions">
   <%= f.submit 'Add Transaction', class: 'btn btn-success'%>
<% end %>  
<%= link_to 'Back', bank_accounts_path, class: "btn btn-default" %>
</div>
</center>

app/views/transactions/edit.html.erb
<center> <%= render 'form' %> </center>

<center><%= link_to 'Show', @transaction %> |
<%= link_to 'Back', :back %></center>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Reference</th>
      <th>Bank</th>
      <th>Account</th>
      <th>Purchase invoice</th>
      <th>Sales invoice</th>
      <th>Contact</th>
      <th>Vat amount</th>
      <th>Vat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.date %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.reference %></td>
        <td><%= transaction.bank_id %></td>
        <td><%= transaction.account_id %></td>
        <td><%= transaction.purchase_invoice_id %></td>
        <td><%= transaction.sales_invoice_id %></td>
        <td><%= transaction.contact_id %></td>
        <td><%= transaction.vat_amount %></td>
        <td><%= transaction.vat %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<center><%= render 'form' %></center>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

  <strong>Amount:</strong>
  <%= @transaction.net_amount %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @transaction.reference %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @transaction.bank_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @transaction.account_id %>
</p>

<p>
  <strong>Purchase invoice:</strong>
  <%= @transaction.purchase_invoice_id %>
</p>

<p>
  <strong>Sales invoice:</strong>
  <%= @transaction.sales_invoice_id %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @transaction.contact_id %>
</p>

<p>
  <strong>Vat amount:</strong>
  <%= @transaction.vat_amount %>
</p>

<p>
  <strong>Vat:</strong>
  <%= @transaction.vat %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>